# Generated Makefile for sysCmpImplB1

TARGETS=sysCmpModImplB1 sysCmpSupModImplB1 
default: $(TARGETS)

clean:
	cd sysCmpModImplB1 ; make -f Makefile clean
	cd sysCmpSupModImplB1 ; make -f Makefile clean

sysCmpModImplB1: dummy
	cd sysCmpModImplB1 ; make -f Makefile

sysCmpSupModImplB1: dummy
	cd sysCmpSupModImplB1 ; make -f Makefile

dummy:
	true
