# Generated Makefile for Component Implementations

TARGETS=sysCmpImplB1 sysCmpImplA1 
default: $(TARGETS)

clean:
	cd sysCmpImplB1 ; make -f Makefile clean
	cd sysCmpImplA1 ; make -f Makefile clean

sysCmpImplB1: dummy
	cd sysCmpImplB1 ; make -f Makefile

sysCmpImplA1: dummy
	cd sysCmpImplA1 ; make -f Makefile

dummy:
	true
