# Generated Makefile for Component Implementations

TARGETS=HelloServer HelloClient 
default: $(TARGETS)

clean:
	cd HelloServer ; make -f Makefile clean
	cd HelloClient ; make -f Makefile clean

HelloServer: dummy
	cd HelloServer ; make -f Makefile

HelloClient: dummy
	cd HelloClient ; make -f Makefile

dummy:
	true
