# Generated Makefile for HelloServer

TARGETS=HSSup HSFunc 
default: $(TARGETS)

clean:
	cd HSSup ; make -f Makefile clean
	cd HSFunc ; make -f Makefile clean

HSSup: dummy
	cd HSSup ; make -f Makefile

HSFunc: dummy
	cd HSFunc ; make -f Makefile

dummy:
	true
