# Generated Makefile for sysCmpImplA1

TARGETS=sysCmpModImplA1 sysCmpSupModImplA1 
default: $(TARGETS)

clean:
	cd sysCmpModImplA1 ; make -f Makefile clean
	cd sysCmpSupModImplA1 ; make -f Makefile clean

sysCmpModImplA1: dummy
	cd sysCmpModImplA1 ; make -f Makefile

sysCmpSupModImplA1: dummy
	cd sysCmpSupModImplA1 ; make -f Makefile

dummy:
	true
