# Generated Makefile for HelloClient

TARGETS=HCFunc HCSup 
default: $(TARGETS)

clean:
	cd HCFunc ; make -f Makefile clean
	cd HCSup ; make -f Makefile clean

HCFunc: dummy
	cd HCFunc ; make -f Makefile

HCSup: dummy
	cd HCSup ; make -f Makefile

dummy:
	true
